[build]
  command = "npm run build"
  publish = "dist/demo"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-angular"
  [plugins.inputs]
    runtime = "none"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
